---
- name: Setup Basic System
  hosts: localhost
  #gather_facts: no
  become: true
  vars_files:
    - vars/default.yml

  pre_tasks:
    - name: Install python for Ansible to work.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

  tasks:
    #- name: Insert UFW Docker fix at the end of after.rules file
     # lineinfile:
      #  path: /etc/ufw/after.rules
       # line: last
     - name: apt update and upgrade
       apt:
         update_cache: yes
         upgrade: yes

     - name: install list of packages from vars
       apt: name={{ sys_packages }} state=latest

     - name: enable ufw
       ufw:
         state: enabled
       
     - name: Download and import ZeroTier pgp key
       apt_key:
         url: "https://download.zerotier.com/contact@zerotier.com.gpg"
       become: yes
 
     - name: Add ZeroTier APT repo
       apt_repository:
         repo: deb http://download.zerotier.com/debian/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main
         filename: zerotier
       register: zerotier_repo
 
     - name: Update APT cache and Install ZeroTier from APT
       apt:
         name: zerotier-one
         update_cache: yes
         autoclean: yes
         autoremove: yes

     - name: allow ssh
       ufw:
         rule: allow
         name: OpenSSH

     - name: deny all other incoming traffic by default
       ufw:
         policy: deny
         direction: incoming
